name: build-win64

permissions:
  contents: write
  
on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository.
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-2022
    steps:
    
    - name: Setup llvm-msvc
      uses: backengineering/setup-llvm-msvc@v5
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        cmake -Bbuild_x64 -Ax64 -TLLVM-MSVC_v143 -DENABLE_TEST=1
        cmake --build build_x64 --config Release --clean-first
    
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-x64-${{ github.run_number }}
        path: |
          build_x64/Release
    
    - name: Compress artifacts
      uses: vimtor/action-zip@26a249fb00d43ca98dad77a4b3838025fc226aa1 # v1.1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: |
         build_x64/Release/*.*
        dest: ${{ github.event.repository.name }}-x64.zip

    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: ${{ github.event.repository.name }}-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
